# Generated by Django 3.2.9 on 2022-03-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar',
        ),
    ]
