# Generated by Django 3.2.9 on 2022-03-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_article_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='signInTime',
        ),
    ]
