# Generated by Django 3.2.9 on 2022-03-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_account_signintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.IntegerField(default=0),
        ),
    ]
