# Generated by Django 3.2.9 on 2022-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(height_field='url_height', upload_to='avatar', width_field='url_height'),
        ),
    ]
